<?php
require_once __DIR__ . '/includes/firebase.php';
require_once __DIR__ . '/classes/UserManager.php';
require_once __DIR__ . '/classes/AttendanceManager.php';
require_once __DIR__ . '/fpdf/fpdf.php';

if (!isset($_POST['user_id']) || !isset($_POST['month'])) {
    die("User and month are required.");
}

$userId = $_POST['user_id'];
$selectedMonth = $_POST['month']; // format: YYYY-MM

$userManager = new UserManager();
$users       = $userManager->getAllUsers();
$user        = $users[$userId] ?? ['name' => $userId];

// שימוש ב־AttendanceManager
$attManager = new AttendanceManager();
$year       = substr($selectedMonth, 0, 4);
$month      = substr($selectedMonth, 5, 2);
$filtered   = $attManager->getAttendanceRecords($userId, $year, $month);

class PDF extends FPDF {
    function Header() {
        $this->Image(__DIR__ . '/assets/logo.png', 10, 10, 30);
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'EasyAttend', 0, 1, 'R');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, 'Phone: 055-1234567', 0, 1, 'R');
        $this->Ln(10);
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 10, 'Monthly Attendance Report', 0, 1, 'C');
        $this->Ln(5);
    }

    function Footer() {
        $this->SetY(-35);
        $this->SetFont('Arial', '', 11);
        $this->Cell(0, 6, 'Manager Signature: ________________________', 0, 1, 'L');
        $this->Ln(5);
        $this->SetFont('Arial','I',8);
        $this->Cell(0, 10, 'Generated by EasyAttend System | Page '.$this->PageNo(), 0, 0, 'C');
    }

    function FancyTable($header, $data) {
        $this->SetFillColor(230, 230, 230);
        $this->SetDrawColor(180, 180, 180);
        $this->SetTextColor(0);
        $this->SetLineWidth(.3);
        $this->SetFont('Arial', 'B', 11);

        $w = [25, 20, 25, 25, 25, 25];
        foreach ($header as $i => $col) {
            $this->Cell($w[$i], 10, $col, 1, 0, 'C', true);
        }
        $this->Ln();

        $this->SetFont('Arial','',10);
        $fill = false;
        foreach ($data as $row) {
            $this->Cell($w[0], 10, $row['date'],      'LR', 0, 'C', $fill);
            $this->Cell($w[1], 10, $row['status'],    'LR', 0, 'C', $fill);
            $this->Cell($w[2], 10, $row['check_in'],  'LR', 0, 'C', $fill);
            $this->Cell($w[3], 10, $row['check_out'], 'LR', 0, 'C', $fill);
            $this->Cell($w[4], 10, $row['total_hours'],'LR', 0, 'C', $fill);
            $this->Cell($w[5], 10, $row['extra_hours'],'LR', 0, 'C', $fill);
            $this->Ln();
            $fill = !$fill;
        }
        $this->Cell(array_sum($w), 0, '', 'T');
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 8, 'Employee Name: ' . $user['name'], 0, 1);
$pdf->Cell(0, 8, 'Employee Username: ' . $userId, 0, 1);
$pdf->Cell(0, 8, 'Report Month: ' . $selectedMonth, 0, 1);
$pdf->Ln(5);

$header    = ['Date', 'Status', 'Check In', 'Check Out', 'Total Hours', 'Extra Hours'];
$tableData = [];

foreach ($filtered as $date => $record) {
    $shifts = $record['shifts'] ?? [];
    if (!empty($shifts)) {
        foreach ($shifts as $index => $shift) {
            $tableData[] = [
                'date'        => ($index === 0 ? $date : ''),
                'status'      => ucfirst($shift['status'] ?? '-'),
                'check_in'    => $shift['check_in'] ?? '-',
                'check_out'   => $shift['check_out'] ?? '-',
                'total_hours' => $shift['total_hours'] ?? '0',
                'extra_hours' => ($index === 0 ? ($record['extra_hours'] ?? '0') : '')
            ];
        }
    } else {
        $tableData[] = [
            'date'        => $date,
            'status'      => ucfirst($record['status'] ?? '-'),
            'check_in'    => '-',
            'check_out'   => '-',
            'total_hours' => '0',
            'extra_hours' => $record['extra_hours'] ?? '0'
        ];
    }
}

$pdf->FancyTable($header, $tableData);

// חישוב סיכומים חודשי (מתבסס על shifts)
$totalMonthHours = 0;
$totalMonthExtra = 0;
foreach ($filtered as $record) {
    $shifts = $record['shifts'] ?? [];
    foreach ($shifts as $shift) {
        if (($shift['status'] ?? '') === 'present') {
            $h = floatval($shift['total_hours'] ?? 0);
            $totalMonthHours += $h;
            $totalMonthExtra += max(0, $h - 8);
        }
    }
}

$pdf->Ln(8);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, "Total Month Hours: $totalMonthHours", 0, 1);
$pdf->Cell(0, 8, "Total Extra Hours: $totalMonthExtra", 0, 1);

$pdf->Output('I', "Attendance_Report_{$userId}_{$selectedMonth}.pdf");
?>